### ISSUE TITLE
Mac users

### ISSUE THREAD

**Issue by AbbyKimball** [Nicola17/High-Dimensional-Inspector#2]
Is there a way to use the HSNE algorithm without Cytosplore? Like in R? I am on a mac and cannot get Cytosplore.

**Comment by Nicola17** [comment]
Hi Abby, HSNE is implemented in C++ and there is no wrapper for R at the moment.
You can build the library using CMake, and use this application (https://github.com/Nicola17/High-Dimensional-Inspector/blob/master/applications/command_line_tools/hsne_cmd.cpp) for running HSNE.
I'll try to make a guide ASAP

**Comment by AbbyKimball** [comment]
Thank you!

**Comment by Nicola17** [comment]
I updated the library and the README with the information on how to build the library in Ubuntu 16.04.
I still have to write the tutorial on HSNE but in the meantime you can try to build it on your system.
I don't have a a Mac at hand but @thoellt built it successfully.
