### ISSUE TITLE
Roaring dependency

### ISSUE THREAD

**Issue by paulderaadt** [Nicola17/High-Dimensional-Inspector#9]
Hi Nicola,

During installation I also found roaring to be a required dependency, I got it from 
https://github.com/RoaringBitmap/CRoaring

**Comment by Nicola17** [comment]
Hey,
indeed you are right!

you can use this 
[script](https://github.com/Nicola17/High-Dimensional-Inspector/blob/master/scripts/install-dependencies.sh) to make the process more streamlined:
I'll update the docs accordingly :)

**Comment by paulderaadt** [comment]
I'm sorry, I did not see the dependencies script. I just followed the readme build instructions and found roaring was missing.

**Comment by Nicola17** [comment]
It's my bad, thank you for pointing out!
I updated the README
